export const Auth = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
};

export const Booking = {
  ALL_DOCTORS: 'ALL_DOCTORS',
  GET_DOC_ID: 'GET_DOC_ID',
  ONE_DOCTOR: 'ONE_DOCTOR',
  ALL_RESERVATIONS: 'ALL_RESERVATIONS',
  ONE_RESERVATION: 'ONE_RESERVATION',
  CREATE_RESERVATION: 'CREATE_RESERVATION',
};
